spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'

      routes:
        - id: bing-route
          uri: https://cn.bing.com/ # 微服务可以采用lb，也可以选择直接地址
          predicates:
            # 全写法
            - name: Path
              args:
                patterns: /search
            - name: Query     # Query断言，必须要匹配对应的参数和值才能响应请求
              args:
                param: q
                regexp: haha
#            - Vip=user,leifengyang
            - name: Vip     # 自定义断言工厂
              args:
                param: user
                value: leifengyang
          order: 10
          metadata:
            hello: world
        - id: order-route   # 路由名称
          uri: lb://service-order   # 负载均衡地址
          predicates:
            - name: Path  # 断言名
              args:
                patterns: /api/order/**   # 请求路由的模式
                matchTrailingSlash: true    # 匹配斜线
          filters:
            - RewritePath=/api/order/?(?<segment>.*), /$\{segment}
            - OnceToken=X-Response-Token, jwt
          order: 1
        - id: product-route
          uri: lb://service-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*), /$\{segment}
          order: 2
      default-filters:
        - AddResponseHeader=X-Response-Abc, 123